In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_pickle("../data/pkl/merged_filtered_0630.pkl")

In [4]:
data

뉴스 식별자        일자   언론사     기고자  \
1        1500701.201604  19911212  부산일보    부산일보   
2        1100611.201604  19911208  서울신문     NaN   
3        1100611.201604  19911206  서울신문     NaN   
4        1100701.199112  19911206  세계일보     김기현   
5        1100901.199111  19911128  중앙일보     NaN   
...                 ...       ...   ...     ...   
5988130  1200101.201604  20140103  경기일보  박상돈 기자   
5988133  1400501.201401  20140102  중부일보     NaN   
5988134  1200101.201604  20140102  경기일보  이호준 기자   
5988139  1200201.201401  20140101  경인일보     NaN   
5988140  1200201.201401  20140101  경인일보     황성규   

                                      제목         통합 분류1     통합 분류2  \
1                                   [사람]          지역>대전      지역>부산   
2                 농수산물 음성정보/74개 시 군으로 확대  IT_과학>인터넷_SNS   IT_과학>과학   
3        뇌물 받고 서류 위조/피해보상금 받게해/공무원등 둘 구속          지역>부산   사회>사건_사고   
4               허위서류 꾸며 보상금/뇌물 받은 공무원 구속          지역>부산   사회>사건_사고   
5                   청와대 비서 사칭 백90억 사기 미수       사회>사건_사고   사회>노동_복지   
...                                  ...            ...        ...   
5988130                 현안 전과정 공개 ‘소통시정’            미분류        NaN   
5988133    대규모 산업단지 조성사업 엇갈린 운명 '시장 뜻따라'          지역>경기      지역>전북   
5988134    [지방자치, 해법을 묻다] 임창열 민선 2기 경기지사        정치>정치일반        NaN   
5988139               2013년 마지막까지 줄이은 화마       사회>사건_사고    사회>사회일반   
5988140               2013년 마지막까지 줄이은 화마       사회>사건_사고        NaN   

             통합 분류3   사건/사고 분류1    사건/사고 분류2  ...  \
1             지역>충남         NaN          NaN  ...   
2         IT_과학>모바일         NaN          NaN  ...   
3             지역>강원  범죄>정치>뇌물수수   범죄>범죄일반>사기  ...   
4             지역>전북  범죄>정치>뇌물수수   범죄>범죄일반>사기  ...   
5           정치>정치일반  범죄>범죄일반>사기          NaN  ...   
...             ...         ...          ...  ...   
5988130         NaN         NaN          NaN  ...   
5988133      경제>부동산         NaN          NaN  ...   
5988134         NaN         NaN          NaN  ...   
5988139         NaN  사고>산업사고>화재          NaN  ...   
5988140         NaN  사고>산업사고>화재          NaN  ...   

                                                        위치  \
1                                            전남,최고경영자,凡一6동   
2                                            김해시,홍성군,서울,부산   
3                                     김해시,외동,구포1동,북구,경남,부산   
4                             김해시,부산시,낙동강,외동,구포1동,북구,경남,남원   
5                         김해시,대성동,10만3천평,서울,부산,쌍림동,(주)대도건설   
...                                                    ...   
5988130                                           연풍,운정,문산   
5988133      피해,경기,파주,도일동,파주시,운정3지구,평택시,평택,법원읍,평택브레인시티,경기도   
5988134  세종시,서울,대중국,경기,한류월드,평택항,경기도,수도권,경기북,시흥,경기지사,경기지...   
5988139                            곤지암읍,경기도내,파주,광주시,파주시,광주   
5988140                            곤지암읍,경기도내,파주,광주시,파주시,광주   

                                                        기관  \
1        金泉시의회,알래스카간,KBS홀,여성단체협의회장,동력자원부,모금추진위원회,학교,농림수...   
2                                             농수산물유통공사,농수산   
3                                            부산지검,김해군청,특수부   
4                                             부산지검,검찰,김해군청   
5                                           정부,경찰청,청와대,특수대   
...                                                    ...   
5988130                                           파주시,파주시청   
5988133  news,평택시장,파주시장,평택브레인시티통합지주협의회,평택브레인시티개발주식회사,법원...   
5988134  지역신용보증재단법,서울대,명지대학교대학원,평택항,미래산업,LG필립스 산업단지,경기도...   
5988139                               금촌동,신촌리,경찰,국립과학수사연구원   
5988140                               금촌동,신촌리,경찰,국립과학수사연구원   

                                                       키워드  \
1        사람,국제통상,주제,강연,전무,金殷湘,한국무역협회,11일,6시,강의실,부산대,경영,...   
2        농수산물,음성,정보,74개,확대,농수산물유통공사,7일,농수산물,정보,음성,서비스,제...   
3        뇌물,서류,위조,피해보상금,공무원등,구속,부산,부산지검,특수,임태성,검사,뇌물,허위...   
4        허위서류,보상금,뇌물,공무원,구속,임태성검사,부산지검,특수,임태성,검사,뇌물,허위,...   
5        청와대,비서,사칭,사기,미수,영장,3명,수배,경찰청,특수대,비서관,청와대,행세,건설...   
...                                                    ...   
59

In [3]:
cat_dict = {
    'topic1' : ['발생', '피해'],
    'topic2' : ['건설', '유치', '인프라'],
    'topic3' : ['개최', '관광', '체험', '국제'],
    'topic4' : ['활성화', '지역경제'],
    'topic5' : ['인구', '감소'],
    'topic6' : ['도심'],
    'topic7' : ['산업'],
    'topic8' : ['주민']
    }

In [4]:
import itertools
key = set(list(itertools.chain.from_iterable(cat_dict.values())))

In [5]:
idx_lst = []
for idx, tokens in enumerate(data['특성추출(가중치순 상위 50개)']):
    toks =  str(tokens).split(',')
    try:
        if len(set(toks).intersection(key)) > 0:
            idx_lst.append(idx)
    except:
        pass


In [11]:
print(data.shape)
data_use = data.iloc[idx_lst,:]
print(data_use.shape)

(4964640, 22)
(802345, 22)


In [41]:
article_topic_mat = np.zeros((8, data_use.shape[0]))
print(article_topic_mat)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [43]:
for topic, item in enumerate(cat_dict):
    cat_key = set(cat_dict[item])
    for idx, tokens in enumerate(data_use['특성추출(가중치순 상위 50개)']):
        toks =  str(tokens).split(',')
        if len(set(toks).intersection(cat_key)) > 0:
            article_topic_mat[topic, idx] = 1

In [48]:
data_use.to_csv("../data/topic_data.csv")
np.savetxt('../result/topic_idx.csv', article_topic_mat, delimiter=",")